/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eVOTE;

import static eVOTE.register.encryptMessage;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author IMO
 */
public class sigin extends javax.swing.JFrame {

    /**
     * Creates new form sigin
     */
    public sigin() {
        initComponents();
    }

    public static String encryptMessage (String message, int key){
        int i = 0;
        char[] chars = message.toCharArray();
        for (i=0; i < chars.length; i++){
            chars[i]+=key;
        }
        return new String(chars);
    }
     public static String decryptMessage (String message, int key){
         int i = 0;
        char[] chars = message.toCharArray();
            for (i=0; i < chars.length; i++){
            chars[i]-=key;
        }
        return new String(chars);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_email = new javax.swing.JLabel();
        canvas1 = new java.awt.Canvas();
        jPanel1 = new javax.swing.JPanel();
        lb_sigin = new javax.swing.JLabel();
        lb_Email = new javax.swing.JLabel();
        login_email = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        login_password = new javax.swing.JPasswordField();
        login_button = new javax.swing.JButton();
        lb_remember = new javax.swing.JCheckBox();
        lb_forgot = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        backToHome = new javax.swing.JButton();

        lb_email.setFont(new java.awt.Font("SimSun-ExtB", 1, 18)); // NOI18N
        lb_email.setText("Enter your Voter ID:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_sigin.setFont(new java.awt.Font("Stencil", 3, 24)); // NOI18N
        lb_sigin.setForeground(new java.awt.Color(204, 204, 255));
        lb_sigin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_sigin.setText("Account Needed");
        lb_sigin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lb_sigin, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 18, 432, 62));

        lb_Email.setFont(new java.awt.Font("Poor Richard", 0, 14)); // NOI18N
        lb_Email.setForeground(new java.awt.Color(255, 255, 255));
        lb_Email.setText("Email:");
        jPanel1.add(lb_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 86, 139, 20));

        login_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_emailActionPerformed(evt);
            }
        });
        jPanel1.add(login_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 112, 349, 30));

        jLabel1.setFont(new java.awt.Font("Poor Richard", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Password: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 148, 116, 19));

        login_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_passwordActionPerformed(evt);
            }
        });
        jPanel1.add(login_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 173, 349, 30));

        login_button.setBackground(new java.awt.Color(51, 153, 255));
        login_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        login_button.setForeground(new java.awt.Color(255, 255, 255));
        login_button.setText("LOG IN");
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(login_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 280, 175, 34));

        lb_remember.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        lb_remember.setForeground(new java.awt.Color(204, 255, 255));
        lb_remember.setText("Remember password?");
        jPanel1.add(lb_remember, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 215, -1, -1));

        lb_forgot.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        lb_forgot.setForeground(new java.awt.Color(204, 255, 255));
        lb_forgot.setText("Forgot password?");
        jPanel1.add(lb_forgot, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 217, 106, -1));

        jPanel2.setBackground(new java.awt.Color(0, 79, 79));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("WELCOME");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 48, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 51, 255));
        jButton1.setText("Log In");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 113, 124, 31));

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setText("Register");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 162, 124, 32));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 270, 380));

        backToHome.setText("Go to Home");
        backToHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToHomeActionPerformed(evt);
            }
        });
        jPanel1.add(backToHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        String email = login_email.getText();
        String password = login_password.getText();
        
        try {
            java.io.FileReader fileReader = new java.io.FileReader("C:\\Users\\IMO\\Documents\\grisliCodes\\userAccs.txt");
            java.util.Scanner fileScanner = new java.util.Scanner(fileReader);

            String storedVoterId = "";
            String storedEmail = "";
            String encryptedPassword = ""; 

            while(fileScanner.hasNextLine()) {
                String line = fileScanner.nextLine();
                String[] parts = line.split(",");//if maka detect, mag split sya

                if (parts.length == 3) {
                    storedVoterId = parts[0]; //PART 0 IS LEFT, THE USER ID
                    storedEmail = parts[1]; //PART 1 IS MIDDLE, THE EMAIL
                    encryptedPassword = parts [2]; //PART 2 IS RIGHT, THE PASSWORD
                    
                    
                }
            }

            fileScanner.close();
            fileReader.close();
            
            int key = 3;
            String decryptedPassword = decryptMessage(encryptedPassword, key);

            // Decrypt password

            // Validate credentials
            if(email.equals(storedEmail) && password.equals(decryptedPassword)) {
                JOptionPane.showMessageDialog(this, "Logged in successfully!");
                
                login login = new login();
                login.setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Invalid email/password.");
            }
        } catch (IOException e) {
            System.out.println("An error occurred during login.");
            e.printStackTrace();
        }
    }//GEN-LAST:event_login_buttonActionPerformed

    private void login_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_passwordActionPerformed
        String password = login_password.getText();
    }//GEN-LAST:event_login_passwordActionPerformed

    private void login_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_emailActionPerformed
        String email = login_email.getText();
    }//GEN-LAST:event_login_emailActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        register acc = new register();
        acc.setVisible(true);
        dispose();
        
//        jDesktopPanel.removeAll();
//        jDesktopPanel.add(acc).setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        sigin id = new sigin();
        id.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void backToHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToHomeActionPerformed
        // TODO add your handling code here:
        login login = new login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_backToHomeActionPerformed

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(sigin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sigin().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToHome;
    private java.awt.Canvas canvas1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb_Email;
    private javax.swing.JLabel lb_email;
    private javax.swing.JLabel lb_forgot;
    private javax.swing.JCheckBox lb_remember;
    private javax.swing.JLabel lb_sigin;
    private javax.swing.JButton login_button;
    private javax.swing.JTextField login_email;
    private javax.swing.JPasswordField login_password;
    // End of variables declaration//GEN-END:variables
}
