/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eVOTE;

import static eVOTE.register.encryptMessage;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author IMO
 */
public class votersDash extends javax.swing.JFrame {

    /**
     * Creates new form candidates
     */
    
    private String voterId;
    
    public votersDash(String voterId) {
        this.voterId = voterId;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        back_button = new javax.swing.JButton();
        presidentCepada = new javax.swing.JButton();
        presidentAraes = new javax.swing.JButton();
        presidentDairo = new javax.swing.JButton();
        presidentInloran = new javax.swing.JButton();
        VPCepada = new javax.swing.JButton();
        VPDairo = new javax.swing.JButton();
        VPAraes = new javax.swing.JButton();
        VPInloran = new javax.swing.JButton();
        SecretaryCepada = new javax.swing.JButton();
        SecretaryDairo = new javax.swing.JButton();
        SecretaryAraes = new javax.swing.JButton();
        SecretaryInloran = new javax.swing.JButton();
        TreasurerCepada = new javax.swing.JButton();
        TreasurerDairo = new javax.swing.JButton();
        TreasurerAraes = new javax.swing.JButton();
        TreasurerInloran = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        chosenSecretary = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        chosenPresident = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        chosenVicePresident = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        chosenTreasurer = new javax.swing.JTextPane();
        submitVoteButton = new javax.swing.JButton();

        jButton4.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PRESIDENT");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("VICE PRESIDENT");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SECRETARY");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TREASURER");

        back_button.setBackground(new java.awt.Color(0, 61, 61));
        back_button.setForeground(new java.awt.Color(204, 204, 255));
        back_button.setText("<<");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        presidentCepada.setBackground(new java.awt.Color(0, 61, 61));
        presidentCepada.setForeground(new java.awt.Color(255, 255, 255));
        presidentCepada.setText("Cepada");
        presidentCepada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presidentCepadaActionPerformed(evt);
            }
        });

        presidentAraes.setBackground(new java.awt.Color(0, 61, 61));
        presidentAraes.setForeground(new java.awt.Color(255, 255, 255));
        presidentAraes.setText("Araes");
        presidentAraes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presidentAraesActionPerformed(evt);
            }
        });

        presidentDairo.setBackground(new java.awt.Color(0, 61, 61));
        presidentDairo.setForeground(new java.awt.Color(255, 255, 255));
        presidentDairo.setText("Dairo");
        presidentDairo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presidentDairoActionPerformed(evt);
            }
        });

        presidentInloran.setBackground(new java.awt.Color(0, 61, 61));
        presidentInloran.setForeground(new java.awt.Color(255, 255, 255));
        presidentInloran.setText("Inloran");
        presidentInloran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presidentInloranActionPerformed(evt);
            }
        });

        VPCepada.setBackground(new java.awt.Color(0, 61, 61));
        VPCepada.setForeground(new java.awt.Color(255, 255, 255));
        VPCepada.setText("Cepada");
        VPCepada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VPCepadaActionPerformed(evt);
            }
        });

        VPDairo.setBackground(new java.awt.Color(0, 61, 61));
        VPDairo.setForeground(new java.awt.Color(255, 255, 255));
        VPDairo.setText("Dairo");
        VPDairo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VPDairoActionPerformed(evt);
            }
        });

        VPAraes.setBackground(new java.awt.Color(0, 61, 61));
        VPAraes.setForeground(new java.awt.Color(255, 255, 255));
        VPAraes.setText("Araes");
        VPAraes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VPAraesActionPerformed(evt);
            }
        });

        VPInloran.setBackground(new java.awt.Color(0, 61, 61));
        VPInloran.setForeground(new java.awt.Color(255, 255, 255));
        VPInloran.setText("Inloran");
        VPInloran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VPInloranActionPerformed(evt);
            }
        });

        SecretaryCepada.setBackground(new java.awt.Color(0, 61, 61));
        SecretaryCepada.setForeground(new java.awt.Color(255, 255, 255));
        SecretaryCepada.setText("Cepada");
        SecretaryCepada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecretaryCepadaActionPerformed(evt);
            }
        });

        SecretaryDairo.setBackground(new java.awt.Color(0, 61, 61));
        SecretaryDairo.setForeground(new java.awt.Color(255, 255, 255));
        SecretaryDairo.setText("Dairo");
        SecretaryDairo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecretaryDairoActionPerformed(evt);
            }
        });

        SecretaryAraes.setBackground(new java.awt.Color(0, 61, 61));
        SecretaryAraes.setForeground(new java.awt.Color(255, 255, 255));
        SecretaryAraes.setText("Araes");
        SecretaryAraes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecretaryAraesActionPerformed(evt);
            }
        });

        SecretaryInloran.setBackground(new java.awt.Color(0, 61, 61));
        SecretaryInloran.setForeground(new java.awt.Color(255, 255, 255));
        SecretaryInloran.setText("Inloran");
        SecretaryInloran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecretaryInloranActionPerformed(evt);
            }
        });

        TreasurerCepada.setBackground(new java.awt.Color(0, 61, 61));
        TreasurerCepada.setForeground(new java.awt.Color(255, 255, 255));
        TreasurerCepada.setText("Cepada");
        TreasurerCepada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TreasurerCepadaActionPerformed(evt);
            }
        });

        TreasurerDairo.setBackground(new java.awt.Color(0, 61, 61));
        TreasurerDairo.setForeground(new java.awt.Color(255, 255, 255));
        TreasurerDairo.setText("Dairo");
        TreasurerDairo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TreasurerDairoActionPerformed(evt);
            }
        });

        TreasurerAraes.setBackground(new java.awt.Color(0, 61, 61));
        TreasurerAraes.setForeground(new java.awt.Color(255, 255, 255));
        TreasurerAraes.setText("Araes");
        TreasurerAraes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TreasurerAraesActionPerformed(evt);
            }
        });

        TreasurerInloran.setBackground(new java.awt.Color(0, 61, 61));
        TreasurerInloran.setForeground(new java.awt.Color(255, 255, 255));
        TreasurerInloran.setText("Inloran");
        TreasurerInloran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TreasurerInloranActionPerformed(evt);
            }
        });

        chosenSecretary.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(chosenSecretary);

        chosenPresident.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane2.setViewportView(chosenPresident);

        chosenVicePresident.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane3.setViewportView(chosenVicePresident);

        chosenTreasurer.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane4.setViewportView(chosenTreasurer);

        submitVoteButton.setBackground(new java.awt.Color(0, 51, 255));
        submitVoteButton.setForeground(new java.awt.Color(255, 255, 255));
        submitVoteButton.setText("Submit vote");
        submitVoteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitVoteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(presidentInloran, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(presidentAraes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(presidentDairo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(presidentCepada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(VPInloran, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(VPAraes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(VPDairo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VPCepada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SecretaryInloran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(SecretaryAraes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(SecretaryDairo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SecretaryCepada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TreasurerInloran, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TreasurerAraes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TreasurerDairo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TreasurerCepada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(submitVoteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(presidentCepada, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(presidentDairo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(presidentAraes, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(presidentInloran, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(VPCepada, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VPDairo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VPAraes, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VPInloran, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SecretaryCepada, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SecretaryDairo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SecretaryAraes, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SecretaryInloran, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TreasurerCepada, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TreasurerDairo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TreasurerAraes, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TreasurerInloran, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitVoteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        voting back = new voting();
        back.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_back_buttonActionPerformed

    private void presidentCepadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presidentCepadaActionPerformed
        // TODO add your handling code here:
        String president = "Cepada";
        chosenPresident.setText(president);
    }//GEN-LAST:event_presidentCepadaActionPerformed

    private void presidentAraesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presidentAraesActionPerformed
        // TODO add your handling code here:
        String president = "Araes";
        chosenPresident.setText(president);
    }//GEN-LAST:event_presidentAraesActionPerformed

    private void presidentDairoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presidentDairoActionPerformed
        // TODO add your handling code here:
        String president = "Dairo";
        chosenPresident.setText(president);
    }//GEN-LAST:event_presidentDairoActionPerformed

    private void presidentInloranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presidentInloranActionPerformed
        // TODO add your handling code here:
        String president = "Inloran";
        chosenPresident.setText(president);
    }//GEN-LAST:event_presidentInloranActionPerformed

    private void VPCepadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VPCepadaActionPerformed
        // TODO add your handling code here:
        String vp = "Cepada";
        chosenVicePresident.setText(vp);
    }//GEN-LAST:event_VPCepadaActionPerformed

    private void VPDairoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VPDairoActionPerformed
        // TODO add your handling code here:
        String vp = "Dairo";
        chosenVicePresident.setText(vp);
    }//GEN-LAST:event_VPDairoActionPerformed

    private void VPAraesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VPAraesActionPerformed
        // TODO add your handling code here:
        String vp = "Araes";
        chosenVicePresident.setText(vp);
    }//GEN-LAST:event_VPAraesActionPerformed

    private void VPInloranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VPInloranActionPerformed
        // TODO add your handling code here:
        String vp = "Inloran";
        chosenVicePresident.setText(vp);
    }//GEN-LAST:event_VPInloranActionPerformed

    private void SecretaryCepadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecretaryCepadaActionPerformed
        // TODO add your handling code here:
        String secretary = "Cepada";
        chosenSecretary.setText(secretary);
    }//GEN-LAST:event_SecretaryCepadaActionPerformed

    private void SecretaryDairoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecretaryDairoActionPerformed
        // TODO add your handling code here:
        String secretary = "Dairo";
        chosenSecretary.setText(secretary);
    }//GEN-LAST:event_SecretaryDairoActionPerformed

    private void SecretaryAraesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecretaryAraesActionPerformed
        // TODO add your handling code here:
        String secretary = "Araes";
        chosenSecretary.setText(secretary);
    }//GEN-LAST:event_SecretaryAraesActionPerformed

    private void SecretaryInloranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecretaryInloranActionPerformed
        // TODO add your handling code here:
        String secretary = "Inloran";
        chosenSecretary.setText(secretary);
    }//GEN-LAST:event_SecretaryInloranActionPerformed

    private void TreasurerCepadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TreasurerCepadaActionPerformed
        // TODO add your handling code here:
        String treasurer = "Cepada";
        chosenTreasurer.setText(treasurer);
    }//GEN-LAST:event_TreasurerCepadaActionPerformed

    private void TreasurerDairoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TreasurerDairoActionPerformed
        // TODO add your handling code here:
        String treasurer = "Dairo";
        chosenTreasurer.setText(treasurer);
    }//GEN-LAST:event_TreasurerDairoActionPerformed

    private void TreasurerAraesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TreasurerAraesActionPerformed
        // TODO add your handling code here:
        String treasurer = "Araes";
        chosenTreasurer.setText(treasurer);
    }//GEN-LAST:event_TreasurerAraesActionPerformed

    private void TreasurerInloranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TreasurerInloranActionPerformed
        // TODO add your handling code here:
        String treasurer = "Inloran";
        chosenTreasurer.setText(treasurer);
    }//GEN-LAST:event_TreasurerInloranActionPerformed

    private void submitVoteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitVoteButtonActionPerformed
        // TODO add your handling code here:
        
        String president = chosenPresident.getText();
        String vp = chosenVicePresident.getText();
        String secretary = chosenSecretary.getText();
        String treasurer = chosenTreasurer.getText();
        
        try{
            java.io.FileWriter fw = new java.io.FileWriter("C:\\Users\\IMO\\Documents\\grisliCodes\\voterslist.txt", true);
            java.io.BufferedWriter bw = new java.io.BufferedWriter(fw);
            
            bw.write(voterId + "," + president + "," + vp + "," + secretary + "," + treasurer + "\n");
            bw.close();
            
            JOptionPane.showMessageDialog(this, "Your vote is submitted successfully!");
            
            voting voting = new voting(voterId);
            voting.setVisible(true);
            dispose();
           
        } catch (Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error saving vote");
        }
    }//GEN-LAST:event_submitVoteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(votersDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(votersDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(votersDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(votersDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new votersDash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SecretaryAraes;
    private javax.swing.JButton SecretaryCepada;
    private javax.swing.JButton SecretaryDairo;
    private javax.swing.JButton SecretaryInloran;
    private javax.swing.JButton TreasurerAraes;
    private javax.swing.JButton TreasurerCepada;
    private javax.swing.JButton TreasurerDairo;
    private javax.swing.JButton TreasurerInloran;
    private javax.swing.JButton VPAraes;
    private javax.swing.JButton VPCepada;
    private javax.swing.JButton VPDairo;
    private javax.swing.JButton VPInloran;
    private javax.swing.JButton back_button;
    private javax.swing.JTextPane chosenPresident;
    private javax.swing.JTextPane chosenSecretary;
    private javax.swing.JTextPane chosenTreasurer;
    private javax.swing.JTextPane chosenVicePresident;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton presidentAraes;
    private javax.swing.JButton presidentCepada;
    private javax.swing.JButton presidentDairo;
    private javax.swing.JButton presidentInloran;
    private javax.swing.JButton submitVoteButton;
    // End of variables declaration//GEN-END:variables
}
